### ISSUE TITLE
src/main FIFO (first-in-first-out) overflow

### ISSUE THREAD

**Issue by yonghuatang** [kaizer222/FEEG2001_DroneAssignment#2]
Omitting the delay() function might help.

**Comment by kaizer222** [comment]
FIFO Overload solved by commenting the set I2C clock speed:

`  
// ========================         MPU Setup           ========================//
pinMode (DMP_PIN,OUTPUT);
digitalWrite(DMP_PIN,LOW);
// join I2C bus
  #if I2CDEV_IMPLEMENTATION == I2CDEV_ARDUINO_WIRE
    Wire.begin();
    //Wire.setClock(40000);                //uncommented due to stability issues
  `
